/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.creandocomponentes;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JSlider;
import javax.swing.JTextField;

/**
 *
 * @author sersu
 */
public class ImagenFondoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ImagenFondoPanel
     */
    public ImagenFondoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txfArchivo = new javax.swing.JTextField();
        btnLoadFile = new javax.swing.JButton();
        lblOpacidad = new javax.swing.JLabel();
        sliOpacidad = new javax.swing.JSlider();
        txfOpacidad = new javax.swing.JTextField();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Imagen");

        btnLoadFile.setText("...");
        btnLoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpacidadhdl(evt);
            }
        });

        lblOpacidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblOpacidad.setText("Opacidad:");

        sliOpacidad.setMinorTickSpacing(1);
        sliOpacidad.setValue(100);
        sliOpacidad.setRequestFocusEnabled(false);
        sliOpacidad.setValueIsAdjusting(true);
        sliOpacidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliOpacidadStateChangedhlr(evt);
            }
        });

        txfOpacidad.setText(sliOpacidad.getValue() + "%");
        txfOpacidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txfOpacidadFocusLostHlr(evt);
            }
        });
        txfOpacidad.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txfOpacidadInputMethodTextChangeHlr(evt);
            }
        });
        txfOpacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfOpacidadActionPerformed(evt);
            }
        });
        txfOpacidad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txfOpacidadPropertyChangeHlr(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOpacidad)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(sliOpacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfOpacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadFile))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpacidad)
                    .addComponent(sliOpacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfOpacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpacidadhdl(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpacidadhdl
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);
        
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            this.txfArchivo.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnOpacidadhdl

    private void sliOpacidadStateChangedhlr(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliOpacidadStateChangedhlr
        this.txfOpacidad.setText(((JSlider)evt.getSource()).getValue() + "%");
    }//GEN-LAST:event_sliOpacidadStateChangedhlr

    private void txfOpacidadFocusLostHlr(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txfOpacidadFocusLostHlr
//        String tmp = Integer.toString(this.sliOpacidad.getValue());
//        String txt = ((JTextField)evt.getSource()).getText();
//        
//        if (evt.getSource() != null  &&  txt.matches("[0-9]%")) {
//            try {
//                this.sliOpacidad.setValue(Integer.parseInt( txt.replace('%', '\u0000') ));
//            } catch (NumberFormatException ex) {
//                this.txfOpacidad.setText(tmp + "%");
//            }
//        } else {
//            this.txfOpacidad.setText(tmp + "%");
//        }
    }//GEN-LAST:event_txfOpacidadFocusLostHlr

    private void txfOpacidadPropertyChangeHlr(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txfOpacidadPropertyChangeHlr
//        String tmp = Integer.toString(this.sliOpacidad.getValue());
//        String txt = ((JTextField)evt.getSource()).getText();
//        
//        if (evt.getSource() != null  &&  txt.matches("[0-9]")) {
//            try {
//                this.sliOpacidad.setValue(Integer.parseInt( txt.replace('%', '\u0000') ));
//            } catch (NumberFormatException ex) {
//                this.txfOpacidad.setText(tmp + "%");
//            }
//        } else {
//            this.txfOpacidad.setText(tmp + "%");
//            this.sliOpacidad.setValue(Integer.parseInt("Fail" + txt.replace('%', '\u0000') ));
//        }
    }//GEN-LAST:event_txfOpacidadPropertyChangeHlr

    private void txfOpacidadInputMethodTextChangeHlr(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txfOpacidadInputMethodTextChangeHlr
//        String tmp = Integer.toString(this.sliOpacidad.getValue());
//        String txt = ((JTextField)evt.getSource()).getText();
//        
//        if (evt.getSource() != null  &&  txt.matches("[0-9]")) {
//            try {
//                this.sliOpacidad.setValue(Integer.parseInt( txt.replace('%', '\u0000') ));
//            } catch (NumberFormatException ex) {
//                this.txfOpacidad.setText(tmp + "%");
//            }
//        } else {
//            this.txfOpacidad.setText(tmp + "%");
//            this.sliOpacidad.setValue(Integer.parseInt("Fail" + txt.replace('%', '\u0000') ));
//        }
    }//GEN-LAST:event_txfOpacidadInputMethodTextChangeHlr

    private void txfOpacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfOpacidadActionPerformed
        String tmp = Integer.toString(this.sliOpacidad.getValue());
        String txt = ((JTextField)evt.getSource()).getText();
        Integer opc = Integer.parseInt(txt.replaceAll("%", "")); //txt.replaceAll("%", "") );.replace('%', '\u0000')
        
        if ((!txt.isBlank()  &&  txt.matches("[0-9]+%{0,1}")) &&  
            (opc>=0  &&  opc<=100)) {
                try {
                    this.sliOpacidad.setValue(opc);
                } catch (NumberFormatException ex) {
                    this.sliOpacidad.setValue(opc);
                }
        } else {
            this.txfOpacidad.setText(tmp + "%");
        }
    }//GEN-LAST:event_txfOpacidadActionPerformed

    
    public ImagenFondo getSelectedValue() {
        File f = new File(this.txfArchivo.getText());
        Float opacidad = this.sliOpacidad.getValue() / 100f;
        
        return new ImagenFondo(f, opacidad  );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblOpacidad;
    private javax.swing.JSlider sliOpacidad;
    private javax.swing.JTextField txfArchivo;
    private javax.swing.JTextField txfOpacidad;
    // End of variables declaration//GEN-END:variables
}
